export const copy = {
  appName: "Telo",
  skipToContent: "Skip to main content",
  chats: "Chats",
  searchChats: "Search chats",
  openAccountMenu: "Open account menu",
  savedMessages: "Saved Messages",
  settings: "Settings",
  backToConversation: "Back to conversation",
  back: "Back",
  telegramAccount: "Telegram account",
  openAgent: "Open agent",
  closeAgent: "Close agent",
  agent: "Agent",
  agentNewThread: "New conversation",
  agentHistory: "Conversation history",
  agentNoHistory: "No conversations yet",
  agentSettings: "Agent settings",
  askAgent: "Ask about this workspace…",
  sendMessage: "Send message",
  messagePlaceholder: "Write a message…",
  messageSendFailed: "Message was not sent",
  conversation: "Conversation",
  syncError: "Telegram sync issue",
  connectionOffline: "Waiting for Telegram connection",
  connectionSynchronizing: "Synchronizing Telegram updates",
  agentConversation: "Agent conversation",
  agentEmpty: "Ask about the open chat or visible messages.",
  agentNotConfigured: "Connect an AI provider",
  agentNotConfiguredBody:
    "Add an API key in Agent settings to start a conversation.",
  agentNotConfiguredAction: "Open Agent settings",
  activityDefault: "Working",
  provider: "Provider",
  model: "Model",
  baseUrl: "Base URL",
  apiKey: "API key",
  instructions: "Instructions",
  inspectWorkspace: "Allow workspace inspection",
  save: "Save",
  saved: "Saved",
  saving: "Saving",
  failed: "Failed",
  configureAgent: "Configure agent",
  openAi: "OpenAI",
  compatible: "OpenAI-compatible",
  optional: "Optional",
  apiKeyPlaceholder: "Unchanged when empty",
  telegram: "Telegram",
  telegramSettings: "Telegram connection",
  phoneNumber: "Phone number",
  countryOrRegion: "Country or region",
  searchCountryOrRegion: "Search countries or regions…",
  noCountryOrRegionFound: "No country or region found.",
  connect: "Connect",
  reconnectTelegram: "Reconnect",
  loginValue: "Login code or password",
  loginCode: "Login code",
  password: "Password",
  continue: "Continue",
  signInToTelegram: "Sign in to Telegram",
  signInWithPhone: "Use your phone number to continue.",
  startMessaging: "Start Messaging",
  editPhoneNumber: "Edit phone number",
  credentialsMissing: "This build is missing Telegram application credentials.",
  loading: "Loading",
  loadingChats: "Loading more chats",
  loadingEarlierMessages: "Loading earlier messages",
  noChats: "No chats found",
  unread: "unread",
  muted: "Muted",
  chatActions: "Chat actions",
  markAsRead: "Mark as read",
  markAsUnread: "Mark as unread",
  pinChat: "Pin",
  unpinChat: "Unpin",
  muteChat: "Mute",
  unmuteChat: "Unmute",
  messageActions: "Message actions",
  copyText: "Copy Text",
  copySelectedText: "Copy Selected Text",
  reply: "Reply",
  editMessage: "Edit message",
  cancel: "Cancel",
  replyingTo: "Reply to",
  editingMessage: "Edit message",
  forward: "Forward",
  forwardTo: "Forward to",
  deleteMessage: "Delete",
  deleteMessageConfirm: "Delete this message? This cannot be undone.",
  edited: "edited",
  closeDialog: "Close dialog",
  appearance: "Appearance",
  theme: "Theme",
  themeLight: "Light",
  themeDark: "Dark",
  themeSystem: "System",
  accentColor: "Accent color",
  accentBlue: "Blue",
  accentGreen: "Green",
  accentPurple: "Purple",
  accentRed: "Red",
  accentOrange: "Orange",
  messageTextSize: "Message text size",
  timeFormat: "Time format",
  timeFormatSystem: "System",
  timeFormat12h: "12-hour",
  timeFormat24h: "24-hour",
  messages: "Messages",
  sendWithEnter: "Send with",
  sendWithEnterEnter: "Enter",
  sendWithEnterCmdEnter: "Cmd+Enter",
  logOut: "Log out",
  logOutConfirm: "Confirm log out",
  loggedOut: "Logged out",
  connectionIdle: "Not connected",
  connectionConnecting: "Connecting",
  connectionCode: "Enter the Telegram code",
  connectionPassword: "Enter your Telegram password",
  connectionReady: "Connected",
  notifications: "Notifications",
  notificationsDesktop: "Desktop notifications",
  notificationsDesktopHint:
    "Show a system notification when the agent finishes while the window is unfocused.",
  notifyRunCompleteBody: "Your agent response is ready.",
  typing: "Typing…",
  draftPrefix: "Draft:",
  today: "Today",
  yesterday: "Yesterday",
  jumpToMessage: "Jump to original message",
} as const;
