export const copy = {
  appName: "Telo",
  skipToContent: "Skip to main content",
  chats: "Chats",
  searchChats: "Search chats",
  openAccountMenu: "Open account menu",
  accounts: "Telegram accounts",
  addAccount: "Add account",
  savedMessages: "Saved Messages",
  recentSearches: "Recent",
  clearSearchHistory: "Clear",
  clearSearchHistoryConfirm:
    "Are you sure you want to clear your search history?",
  clearSearchHistoryAction: "Clear history",
  removeFromHistory: "Remove from history",
  noRecentSearches: "Your recent searches will appear here",
  settings: "Settings",
  backToConversation: "Back to conversation",
  back: "Back",
  backToChats: "Back to chats",
  resizeChatList: "Resize chat list",
  resizeAgentPanel: "Resize agent panel",
  telegramAccount: "Telegram account",
  openAgent: "Open agent",
  closeAgent: "Close agent",
  agent: "Agent",
  agentNewThread: "New conversation",
  agentHistory: "Conversation history",
  agentNoHistory: "No conversations yet",
  agentSettings: "Agent settings",
  askAgent: "Ask about this workspace…",
  sendMessage: "Send message",
  messagePlaceholder: "Write a message…",
  messageSendFailed: "Message was not sent",
  messageSending: "Sending",
  messageSent: "Sent",
  messageRead: "Read",
  resendMessage: "Resend",
  conversation: "Conversation",
  // Never painted. E2E and widget tests assert this string is absent.
  syncError: "Telegram sync issue",
  connectionOffline: "Connecting…",
  connectionSynchronizing: "Updating…",
  agentConversation: "Agent conversation",
  agentEmpty: "Ask about the open chat or visible messages.",
  agentSummarizeUnread: "Summarize unread",
  agentExtractInsights: "Extract decisions & todos",
  agentCitations: "Cited messages",
  agentScrollToMessage: "Scroll to message",
  agentCitationUnavailable: "This message is no longer available",
  agentSuggestions: "Suggested prompts",
  agentAttachedMessages: "Messages added to the conversation",
  agentRemoveAttachment: "Remove message",
  agentAddToAgent: "Add to Agent",
  agentThinking: "Thinking",
  agentRunFailed: "Couldn't finish this reply.",
  agentRetry: "Try again",
  agentNotConfigured: "Connect an AI provider",
  agentNotConfiguredBody:
    "Connect a provider in Agent settings to start a conversation.",
  agentNotConfiguredAction: "Open Agent settings",
  activityDefault: "Working",
  provider: "Provider",
  model: "Model",
  baseUrl: "Base URL",
  account: "Account",
  apiKey: "API key",
  connectAccount: "Connect account",
  disconnectAccount: "Disconnect",
  connectingAccount: "Connecting",
  accountConnected: "Connected",
  instructions: "Instructions",
  inspectWorkspace: "Allow workspace inspection",
  save: "Save",
  saved: "Saved",
  saving: "Saving",
  failed: "Failed",
  configureAgent: "Configure agent",
  openAi: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  groq: "Groq",
  xai: "xAI",
  kimi: "Kimi",
  deepseek: "DeepSeek",
  mistral: "Mistral",
  compatible: "OpenAI-compatible",
  searchProvider: "Search providers…",
  noProviderFound: "No provider matches",
  searchModel: "Search models…",
  noModelFound: "No model matches",
  modelsUnavailable: "The model list could not be loaded.",
  optional: "Optional",
  apiKeyPlaceholder: "Unchanged when empty",
  telegram: "Telegram",
  telegramSettings: "Telegram connection",
  phoneNumber: "Phone number",
  countryOrRegion: "Country or region",
  searchCountryOrRegion: "Search countries or regions…",
  noCountryOrRegionFound: "No country or region found.",
  connect: "Connect",
  reconnectTelegram: "Reconnect",
  loginValue: "Login code or password",
  loginCode: "Login code",
  password: "Password",
  continue: "Continue",
  signInToTelegram: "Sign in to Telegram",
  signInWithPhone: "Use your phone number to continue.",
  startMessaging: "Start Messaging",
  editPhoneNumber: "Edit phone number",
  credentialsMissing: "This build is missing Telegram application credentials.",
  addAccountWithPhone: "Use your phone number to sign in to another account.",
  cancelAddAccount: "Cancel adding account",
  loading: "Loading",
  loadingChats: "Loading more chats",
  loadingEarlierMessages: "Loading earlier messages",
  loadingChatList: "Loading chats",
  loadingChatInfo: "Loading chat info",
  loadingStickerSet: "Loading sticker set",
  noChats: "No chats found",
  unread: "unread",
  muted: "Muted",
  chatActions: "Chat actions",
  markAsRead: "Mark as read",
  markAsUnread: "Mark as unread",
  pinChat: "Pin",
  unpinChat: "Unpin",
  muteChat: "Mute",
  unmuteChat: "Unmute",
  messageActions: "Message actions",
  copyText: "Copy Text",
  copySelectedText: "Copy Selected Text",
  reply: "Reply",
  editMessage: "Edit message",
  cancel: "Cancel",
  replyingTo: "Reply to",
  editingMessage: "Edit message",
  forward: "Forward",
  forwardTo: "Forward to",
  forwardHideSender: "Hide sender",
  forwardedFrom: "Forwarded from",
  forwardedSenderHidden: "The account was hidden by the user",
  botKeyboard: "Bot actions",
  botButtonUnsupported: "This action is not available in Telo yet",
  botButtonFailed: "The bot did not answer",
  deleteMessage: "Delete",
  archivedChats: "Archived Chats",
  backToAllChats: "All chats",
  archiveChat: "Archive",
  unarchiveChat: "Unarchive",
  deleteMessageConfirm: "Delete this message? This cannot be undone.",
  edited: "edited",
  closeDialog: "Close dialog",
  appearance: "Appearance",
  theme: "Theme",
  themeLight: "Light",
  themeDark: "Dark",
  themeSystem: "System",
  accentColor: "Accent color",
  accentBlue: "Blue",
  accentGreen: "Green",
  accentPurple: "Purple",
  accentRed: "Red",
  accentOrange: "Orange",
  messageTextSize: "Message text size",
  timeFormat: "Time format",
  timeFormatSystem: "System",
  timeFormat12h: "12-hour",
  timeFormat24h: "24-hour",
  messages: "Messages",
  sendWithEnter: "Send with",
  sendWithEnterEnter: "Enter",
  sendWithEnterCmdEnter: "Cmd+Enter",
  logOut: "Log out",
  logOutConfirm: "Confirm log out",
  loggedOut: "Logged out",
  connectionIdle: "Not connected",
  connectionConnecting: "Connecting",
  connectionCode: "Enter the Telegram code",
  connectionPassword: "Enter your Telegram password",
  connectionReady: "Connected",
  notifications: "Notifications",
  notificationsDesktop: "Desktop notifications",
  notificationsDesktopHint:
    "Show a system notification when the agent finishes while the window is unfocused.",
  notifyRunCompleteBody: "Your agent response is ready.",
  notifyIncomingMessageBody: "New message",
  settingsSearch: "Search settings",
  settingsNoResults: "No settings match",
  settingsAccount: "Account",
  chatSettings: "Chat settings",
  folders: "Folders",
  dataAndStorage: "Data and storage",
  reduceMotion: "Reduce motion",
  reduceMotionHint:
    "Replace slides and springs with plain fades. The system setting still applies when this is off.",
  loopStickers: "Loop animated stickers",
  loopStickersHint:
    "Animated and video stickers replay on their own. When off they hold their first frame behind a play control.",
  notificationSenderName: "Show sender name",
  notificationSenderNameHint:
    "Title the notification with the chat instead of just the app.",
  notificationPreview: "Show message text",
  notificationPreviewHint: "Include the message body instead of a placeholder.",
  countMutedChats: "Count muted chats",
  countMutedChatsHint:
    "Muted chats add to the chat-list and folder unread badges.",
  mediaCache: "Media cache",
  mediaCacheHint:
    "Photos, videos and stickers already downloaded are kept on disk so reopening a chat does not refetch them.",
  mediaCacheUsage: "On disk",
  mediaCacheLimit: "Size limit",
  mediaCacheLimitHint:
    "The oldest files are dropped once the cache passes this size.",
  clearCache: "Clear cache",
  cacheCleared: "Cache cleared",
  accountConnection: "Connection",
  agentProviderGroup: "Provider",
  agentBehaviourGroup: "Behaviour",
  agentTuningGroup: "Tuning",
  agentTemperature: "Temperature",
  agentTemperatureHint:
    "Lower keeps answers predictable; higher lets the model wander.",
  agentMaxSteps: "Tool call rounds",
  agentMaxStepsHint:
    "How many times the agent may read the workspace before it has to answer.",
  agentHistoryLimit: "Replayed turns",
  agentHistoryLimitHint:
    "Earlier turns of the thread sent with each request. Zero sends only the new prompt.",
  typing: "Typing…",
  draftPrefix: "Draft:",
  today: "Today",
  yesterday: "Yesterday",
  jumpToMessage: "Jump to original message",
  jumpToLatestMessages: "Jump to latest messages",
  unreadMessages: "Unread messages",
  revealSpoiler: "Reveal hidden text",
  downloadMedia: "Download attachment",
  cancelDownload: "Cancel download",
  retryDownload: "Retry download",
  mediaDownloadFailed: "Attachment download failed",
  attachFiles: "Attach photos, videos, or files",
  removeAttachment: "Remove attachment",
  tooManyAttachments: "You can send up to 10 attachments at once",
  mediaUploadFailed: "Attachments were not sent",
  attachmentsInEdit: "Attachments can't be sent while editing a message",
  mediaViewer: "Media viewer",
  viewMedia: "View media",
  closeViewer: "Close viewer",
  previousMedia: "Previous media",
  nextMedia: "Next media",
  openMedia: "Open",
  saveMediaAs: "Save as…",
  mediaActionFailed: "The media action failed",
  chatFolders: "Chat folders",
  allChats: "All",
  archiveFolder: "Archive",
  keywordFolders: "Keyword folders",
  keywordFoldersHint:
    "A search term auto-collects chats whose messages contain it, case-insensitive.",
  keywordFolderTitle: "Folder name",
  keywordFolderQuery: "Search term",
  keywordFolderQueryHint:
    "Chats join this folder when any message body contains the term as a substring.",
  addKeywordFolder: "Add keyword folder",
  editKeywordFolder: "Edit keyword folder",
  deleteKeywordFolder: "Delete keyword folder",
  noKeywordFolders: "No keyword folders yet.",
  saveKeywordFolder: "Save folder",
  online: "online",
  pinnedChats: "Pinned",
  loadingAvatar: "Loading photo",
  chatProfile: "Chat info",
  closeChatProfile: "Close chat info",
  userProfile: "Profile",
  openProfile: "Open profile",
  peerBio: "Bio",
  peerPhone: "Phone",
  peerUsername: "Username",
  copied: "Copied",
  sticker: "Sticker",
  playSticker: "Play sticker",
  stickerPicker: "Stickers",
  noStickerSets: "No sticker sets yet.",
  openStickerSet: "Open sticker set",
  addStickerSet: "Add stickers",
  removeStickerSet: "Remove stickers",
  sharedMedia: "Shared media",
  mediaFiles: "Files",
  pinnedMessages: "Pinned messages",
  chatKindGroup: "Group",
  chatKindChannel: "Channel",
  searchMessages: "Search messages",
  searchInChat: "Search in chat",
  closeSearch: "Close search",
  searchMatchOf: "of",
  olderMatch: "Older match",
  newerMatch: "Newer match",
  searchingServer: "Searching…",
  noSearchResults: "No results",
  translateMessage: "Translate",
  rewriteMessage: "Rewrite",
  draftReply: "Draft reply",
  draftReplyToneNeutral: "Neutral",
  draftReplyToneFriendly: "Friendly",
  draftReplyToneFormal: "Formal",
  messageActionFailed: "The AI action failed",
  sendOptions: "Send options",
  sendWithoutSound: "Send without sound",
  emojiPicker: "Emoji",
  mediaPicker: "Emoji and stickers",
  searchEmoji: "Search emoji…",
  noEmojiFound: "No emoji found",
  emojiRecent: "Frequently used",
  emojiCategorySmileys: "Smileys & emotions",
  emojiCategoryPeople: "People & body",
  emojiCategoryAnimals: "Animals & nature",
  emojiCategoryFood: "Food & drink",
  emojiCategoryActivity: "Activity",
  emojiCategoryTravel: "Travel & places",
  emojiCategoryObjects: "Objects",
  emojiCategorySymbols: "Symbols",
  aiActions: "AI actions",
  selectMessage: "Select",
  deselectMessage: "Deselect",
  messagesSelected: "selected",
  exitSelection: "Exit selection",
  selectionActions: "Selection actions",
  deleteForMe: "Delete for me",
  deleteForEveryone: "Delete for everyone",
  deleteMessagesConfirm: "Delete the selected messages? This cannot be undone.",
  searchEverywhere: "Search chats and messages…",
  searchEverywhereLabel: "Search everywhere",
  searchInChatShortcut: "Search in chat (Ctrl+F)",
  messageTemplates: "Templates",
  noMessageTemplates: "No templates yet",
  newMessageTemplate: "New template",
  editMessageTemplate: "Edit template",
  deleteMessageTemplate: "Delete template",
  messageTemplateTitle: "Title",
  messageTemplateBody: "Message",
  saveMessageTemplate: "Save template",
  formatting: "Formatting",
  formatBold: "Bold",
  formatItalic: "Italic",
  formatUnderline: "Underline",
  formatStrikethrough: "Strikethrough",
  formatCode: "Monospace",
  formatSpoiler: "Spoiler",
  formatClear: "Clear formatting",
  composerActions: "Message field actions",
  composerCopy: "Copy",
  composerCut: "Cut",
  composerPaste: "Paste",
  composerSelectAll: "Select all",
  mentionSuggestions: "Mentions",
  triggerRules: "Trigger rules",
  triggerRulesHint:
    "An agent run fires when an incoming message matches every set dimension.",
  noTriggerRules:
    "No trigger rules yet — ask the agent to watch for something, or add one here.",
  addTriggerRule: "Add rule",
  editTriggerRule: "Edit rule",
  deleteTriggerRule: "Delete rule",
  saveTriggerRule: "Save rule",
  toggleTriggerRule: "Toggle rule",
  scheduledTasks: "Scheduled tasks",
  noScheduledTasks:
    "No scheduled tasks yet — ask the agent to schedule one, or add one here.",
  addScheduledTask: "Add task",
  editScheduledTask: "Edit task",
  deleteScheduledTask: "Delete task",
  saveScheduledTask: "Save task",
  toggleScheduledTask: "Toggle task",
  createdByAgent: "Created by the agent",
  delivery: "Delivery",
  deliveryDraftOnly: "Park replies as drafts",
  deliveryAutoSend: "Send replies automatically",
  deliveryDraftOnlyBadge: "Draft",
  deliveryAutoSendBadge: "Auto-send",
  nextRun: "Next run",
  ruleName: "Rule name",
  taskName: "Task name",
  matchChatIds: "Chat IDs",
  matchSenderIds: "Sender IDs",
  matchKeywords: "Keywords",
  matchKeywordsHint: "Comma-separated; any one of them fires the rule.",
  matchIdsHint: "Comma-separated; empty matches everything.",
  matchPattern: "Pattern (regex)",
  matchSkipsMuted: "skips muted chats",
  ruleNeedsMatch: "Set at least one match dimension.",
  invalidPattern: "The pattern is not a valid regular expression.",
  excludeMuted: "Skip muted chats",
  promptTemplate: "Prompt",
  scheduleKind: "Schedule",
  scheduleCron: "Repeating (cron)",
  scheduleOnce: "One time",
  cronExpression: "Cron expression",
  cronExpressionHint:
    "Five fields in local time: minute hour day-of-month month weekday.",
  cronFieldsInvalid: "A cron expression has five fields.",
  runAt: "Run at",
  runAtInvalid: "Pick a date and time to run.",
  targetChatId: "Target chat ID",
  taskContext: "Run with",
  contextNone: "No extra context",
  contextUnread: "Unread messages",
  contextFolder: "A folder",
  folderId: "Folder ID",
} as const;
