/**
 * Curated Unicode emoji dataset for the composer picker. Glyphs and their
 * English search names are data, not copy. Coverage is a compact, hand-picked
 * subset of the full Unicode emoji set — enough for daily messaging, not the
 * complete catalog (no flags, few skin-tone variants).
 */

export type EmojiCategoryId =
  | "smileys"
  | "people"
  | "animals"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols";

export interface EmojiEntry {
  readonly glyph: string;
  /** Lowercase search terms matched against the picker's query. */
  readonly name: string;
}

export interface EmojiCategory {
  readonly id: EmojiCategoryId;
  readonly entries: ReadonlyArray<EmojiEntry>;
}

function category(
  id: EmojiCategoryId,
  entries: ReadonlyArray<readonly [string, string]>,
): EmojiCategory {
  return {
    id,
    entries: entries.map(([glyph, name]) => ({ glyph, name })),
  };
}

export const EMOJI_CATEGORIES: ReadonlyArray<EmojiCategory> = [
  category("smileys", [
    ["😀", "grinning face happy smile"],
    ["😃", "grinning face big eyes happy smile"],
    ["😄", "grinning face smiling eyes happy joy"],
    ["😁", "beaming face smiling eyes grin"],
    ["😆", "grinning squinting face laughing lol"],
    ["😅", "grinning face sweat relief"],
    ["🤣", "rolling on the floor laughing rofl lol"],
    ["😂", "face with tears of joy laughing lol"],
    ["🙂", "slightly smiling face"],
    ["🙃", "upside down face silly"],
    ["😉", "winking face"],
    ["😊", "smiling face smiling eyes blush happy"],
    ["😇", "smiling face halo innocent angel"],
    ["🥰", "smiling face hearts love"],
    ["😍", "smiling face heart eyes love"],
    ["🤩", "star struck excited"],
    ["😘", "face blowing a kiss"],
    ["😗", "kissing face"],
    ["😚", "kissing face closed eyes"],
    ["😋", "face savoring food yum delicious"],
    ["😛", "face tongue out playful"],
    ["😜", "winking face tongue out playful"],
    ["🤪", "zany face crazy"],
    ["😝", "squinting face tongue out playful"],
    ["🤑", "money mouth face rich"],
    ["🤗", "smiling face open hands hug"],
    ["🤭", "face hand over mouth oops giggle"],
    ["🤫", "shushing face quiet secret"],
    ["🤔", "thinking face hmm"],
    ["🫡", "saluting face respect"],
    ["😐", "neutral face meh"],
    ["😑", "expressionless face"],
    ["😶", "face without mouth silent"],
    ["🫥", "dotted line face invisible"],
    ["😏", "smirking face smug"],
    ["😒", "unamused face"],
    ["🙄", "face rolling eyes"],
    ["😬", "grimacing face awkward"],
    ["🤥", "lying face pinocchio"],
    ["😌", "relieved face calm"],
    ["😔", "pensive face sad"],
    ["😪", "sleepy face tired"],
    ["🤤", "drooling face"],
    ["😴", "sleeping face zzz tired"],
    ["😷", "face medical mask sick"],
    ["🤒", "face thermometer sick fever"],
    ["🤕", "face head bandage hurt"],
    ["🤢", "nauseated face sick"],
    ["🤮", "face vomiting sick"],
    ["🤧", "sneezing face sick"],
    ["🥵", "hot face heat sweating"],
    ["🥶", "cold face freezing"],
    ["🥴", "woozy face drunk dizzy"],
    ["😵", "face crossed out eyes dizzy dead"],
    ["🤯", "exploding head mind blown"],
    ["🤠", "cowboy hat face"],
    ["🥳", "partying face celebration birthday"],
    ["🥸", "disguised face"],
    ["😎", "smiling face sunglasses cool"],
    ["🤓", "nerd face glasses geek"],
    ["🧐", "face monocle scrutinizing"],
    ["😕", "confused face"],
    ["🫤", "face diagonal mouth skeptical"],
    ["😟", "worried face"],
    ["🙁", "slightly frowning face sad"],
    ["😮", "face open mouth surprised"],
    ["😯", "hushed face surprised"],
    ["😲", "astonished face shocked"],
    ["😳", "flushed face embarrassed"],
    ["🥺", "pleading face puppy eyes beg"],
    ["😦", "frowning face open mouth"],
    ["😨", "fearful face scared"],
    ["😰", "anxious face sweat nervous"],
    ["😥", "sad but relieved face"],
    ["😢", "crying face sad tear"],
    ["😭", "loudly crying face sobbing"],
    ["😱", "face screaming fear horror"],
    ["😖", "confounded face frustrated"],
    ["😣", "persevering face struggling"],
    ["😞", "disappointed face sad"],
    ["😓", "downcast face sweat"],
    ["😩", "weary face tired"],
    ["😫", "tired face exhausted"],
    ["🥱", "yawning face sleepy bored"],
    ["😤", "face steam from nose triumph angry"],
    ["😡", "enraged face angry mad pouting"],
    ["😠", "angry face mad"],
    ["🤬", "face symbols on mouth cursing swearing"],
    ["😈", "smiling face horns devil"],
    ["💀", "skull dead dying laughing"],
    ["💩", "pile of poo poop"],
    ["🤡", "clown face"],
    ["👻", "ghost halloween spooky"],
    ["👽", "alien ufo"],
    ["🤖", "robot face bot"],
    ["😺", "grinning cat happy"],
    ["😹", "cat tears of joy laughing"],
    ["😻", "smiling cat heart eyes love"],
    ["🙈", "see no evil monkey"],
    ["🙉", "hear no evil monkey"],
    ["🙊", "speak no evil monkey"],
  ]),
  category("people", [
    ["👋", "waving hand hello hi bye"],
    ["🤚", "raised back of hand"],
    ["🖐️", "hand fingers splayed high five"],
    ["✋", "raised hand stop high five"],
    ["🖖", "vulcan salute spock"],
    ["🫱", "rightwards hand"],
    ["🫲", "leftwards hand"],
    ["👌", "ok hand okay perfect"],
    ["🤌", "pinched fingers italian"],
    ["🤏", "pinching hand small little"],
    ["✌️", "victory hand peace"],
    ["🤞", "crossed fingers luck hope"],
    ["🫰", "hand index thumb crossed snap"],
    ["🤟", "love you gesture rock"],
    ["🤘", "sign of the horns rock metal"],
    ["🤙", "call me hand shaka"],
    ["👈", "backhand index pointing left"],
    ["👉", "backhand index pointing right"],
    ["👆", "backhand index pointing up"],
    ["👇", "backhand index pointing down"],
    ["☝️", "index pointing up"],
    ["🫵", "index pointing at the viewer you"],
    ["👍", "thumbs up like yes approve +1"],
    ["👎", "thumbs down dislike no -1"],
    ["✊", "raised fist power"],
    ["👊", "oncoming fist punch bump"],
    ["👏", "clapping hands applause bravo"],
    ["🙌", "raising hands celebration hooray"],
    ["🫶", "heart hands love"],
    ["👐", "open hands hug"],
    ["🤲", "palms up together"],
    ["🤝", "handshake deal agreement"],
    ["🙏", "folded hands please thank you pray"],
    ["✍️", "writing hand"],
    ["💪", "flexed biceps strong muscle"],
    ["🦾", "mechanical arm"],
    ["👀", "eyes looking watching"],
    ["👁️", "eye watching"],
    ["🧠", "brain smart thinking"],
    ["🗣️", "speaking head talk"],
    ["👤", "bust silhouette person"],
    ["👥", "busts silhouette people group"],
    ["🫂", "people hugging"],
    ["👶", "baby child"],
    ["🧒", "child kid"],
    ["👦", "boy child"],
    ["👧", "girl child"],
    ["🧑", "person adult"],
    ["👨", "man"],
    ["👩", "woman"],
    ["🧓", "older person"],
    ["👴", "old man grandfather"],
    ["👵", "old woman grandmother"],
    ["🙍", "person frowning"],
    ["🙎", "person pouting"],
    ["🙅", "person gesturing no"],
    ["🙆", "person gesturing ok"],
    ["💁", "person tipping hand information"],
    ["🙋", "person raising hand question"],
    ["🧏", "deaf person"],
    ["🙇", "person bowing sorry"],
    ["🤦", "person facepalming"],
    ["🤷", "person shrugging dunno whatever"],
    ["🧑‍💻", "technologist developer coder"],
    ["🧑‍🏫", "teacher"],
    ["🧑‍🎨", "artist"],
    ["🧑‍🔬", "scientist"],
    ["🧑‍🚀", "astronaut"],
    ["🦸", "superhero"],
    ["🦹", "supervillain"],
    ["🧙", "mage wizard"],
    ["🧚", "fairy"],
    ["🧛", "vampire"],
    ["🧟", "zombie"],
    ["🏃", "person running runner"],
    ["🚶", "person walking"],
    ["🧍", "person standing"],
    ["🕺", "man dancing"],
    ["💃", "woman dancing dancer"],
    ["🕴️", "person suit levitating"],
    ["👪", "family"],
    ["🏋️", "person lifting weights gym"],
    ["⛹️", "person bouncing ball basketball"],
    ["🤸", "person cartwheeling gymnastics"],
    ["🏊", "person swimming"],
    ["🚴", "person biking cyclist"],
    ["🧘", "person lotus position yoga meditation"],
  ]),
  category("animals", [
    ["🐶", "dog face puppy"],
    ["🐱", "cat face kitten"],
    ["🐭", "mouse face"],
    ["🐹", "hamster"],
    ["🐰", "rabbit face bunny"],
    ["🦊", "fox"],
    ["🐻", "bear"],
    ["🐼", "panda"],
    ["🐨", "koala"],
    ["🐯", "tiger face"],
    ["🦁", "lion"],
    ["🐮", "cow face"],
    ["🐷", "pig face"],
    ["🐸", "frog"],
    ["🐵", "monkey face"],
    ["🐔", "chicken"],
    ["🐧", "penguin"],
    ["🐦", "bird"],
    ["🐤", "baby chick"],
    ["🦆", "duck"],
    ["🦅", "eagle"],
    ["🦉", "owl"],
    ["🦇", "bat"],
    ["🐺", "wolf"],
    ["🐗", "boar"],
    ["🐴", "horse face"],
    ["🦄", "unicorn"],
    ["🐝", "honeybee bee"],
    ["🦋", "butterfly"],
    ["🐌", "snail slow"],
    ["🐞", "lady beetle bug"],
    ["🐜", "ant"],
    ["🕷️", "spider"],
    ["🐢", "turtle slow"],
    ["🐍", "snake"],
    ["🦎", "lizard"],
    ["🐙", "octopus"],
    ["🦑", "squid"],
    ["🦐", "shrimp"],
    ["🦀", "crab"],
    ["🐡", "blowfish"],
    ["🐠", "tropical fish"],
    ["🐟", "fish"],
    ["🐬", "dolphin"],
    ["🐳", "spouting whale"],
    ["🦈", "shark"],
    ["🐊", "crocodile alligator"],
    ["🐘", "elephant"],
    ["🦒", "giraffe"],
    ["🦘", "kangaroo"],
    ["🐎", "horse"],
    ["🐖", "pig"],
    ["🐑", "ewe sheep"],
    ["🐐", "goat"],
    ["🦌", "deer"],
    ["🐕", "dog"],
    ["🐈", "cat"],
    ["🐇", "rabbit bunny"],
    ["🐿️", "chipmunk squirrel"],
    ["🦔", "hedgehog"],
    ["🌵", "cactus desert"],
    ["🌲", "evergreen tree pine"],
    ["🌳", "deciduous tree"],
    ["🌴", "palm tree beach"],
    ["🌱", "seedling plant sprout"],
    ["🍀", "four leaf clover luck"],
    ["🍁", "maple leaf autumn fall canada"],
    ["🍂", "fallen leaf autumn"],
    ["🌾", "sheaf of rice"],
    ["🌺", "hibiscus flower"],
    ["🌻", "sunflower"],
    ["🌹", "rose flower"],
    ["🌷", "tulip flower"],
    ["💐", "bouquet flowers"],
    ["🌸", "cherry blossom flower spring"],
    ["🍄", "mushroom"],
    ["🌍", "globe europe africa earth world"],
    ["🌎", "globe americas earth world"],
    ["🌏", "globe asia australia earth world"],
    ["🌕", "full moon"],
    ["⭐", "star"],
    ["🌟", "glowing star"],
    ["✨", "sparkles magic new"],
    ["⚡", "high voltage lightning zap"],
    ["🔥", "fire hot lit"],
    ["🌈", "rainbow pride"],
    ["☀️", "sun sunny"],
    ["⛅", "sun behind cloud weather"],
    ["☁️", "cloud weather"],
    ["🌧️", "cloud with rain weather"],
    ["⛈️", "cloud lightning rain storm"],
    ["❄️", "snowflake cold winter"],
    ["☃️", "snowman winter"],
    ["🌊", "water wave ocean surf"],
    ["💧", "droplet water"],
    ["☔", "umbrella rain drops weather"],
  ]),
  category("food", [
    ["🍏", "green apple fruit"],
    ["🍎", "red apple fruit"],
    ["🍐", "pear fruit"],
    ["🍊", "tangerine orange fruit"],
    ["🍋", "lemon fruit"],
    ["🍌", "banana fruit"],
    ["🍉", "watermelon fruit"],
    ["🍇", "grapes fruit"],
    ["🍓", "strawberry fruit"],
    ["🫐", "blueberries fruit"],
    ["🍈", "melon fruit"],
    ["🍒", "cherries fruit"],
    ["🍑", "peach fruit"],
    ["🥭", "mango fruit"],
    ["🍍", "pineapple fruit"],
    ["🥥", "coconut"],
    ["🥝", "kiwi fruit"],
    ["🍅", "tomato vegetable"],
    ["🥑", "avocado"],
    ["🥦", "broccoli vegetable"],
    ["🥬", "leafy green vegetable salad"],
    ["🥒", "cucumber pickle"],
    ["🌶️", "hot pepper spicy chili"],
    ["🌽", "ear of corn maize"],
    ["🥕", "carrot vegetable"],
    ["🧄", "garlic"],
    ["🧅", "onion"],
    ["🥔", "potato"],
    ["🍠", "roasted sweet potato"],
    ["🥐", "croissant bread"],
    ["🍞", "bread loaf"],
    ["🥖", "baguette bread"],
    ["🥨", "pretzel"],
    ["🧀", "cheese wedge"],
    ["🥚", "egg"],
    ["🍳", "cooking fried egg breakfast"],
    ["🥞", "pancakes breakfast"],
    ["🧇", "waffle breakfast"],
    ["🥓", "bacon"],
    ["🥩", "cut of meat steak"],
    ["🍗", "poultry leg chicken"],
    ["🌭", "hot dog"],
    ["🍔", "hamburger burger"],
    ["🍟", "french fries"],
    ["🍕", "pizza"],
    ["🥪", "sandwich"],
    ["🌮", "taco mexican"],
    ["🌯", "burrito mexican"],
    ["🥗", "green salad healthy"],
    ["🍝", "spaghetti pasta"],
    ["🍜", "steaming bowl ramen noodles"],
    ["🍲", "pot of food stew soup"],
    ["🍛", "curry rice"],
    ["🍣", "sushi japanese"],
    ["🍱", "bento box japanese"],
    ["🥟", "dumpling"],
    ["🍤", "fried shrimp tempura"],
    ["🍙", "rice ball onigiri"],
    ["🍚", "cooked rice"],
    ["🍥", "fish cake narutomaki"],
    ["🥠", "fortune cookie"],
    ["🍢", "oden skewer"],
    ["🍡", "dango"],
    ["🍧", "shaved ice dessert"],
    ["🍨", "ice cream dessert"],
    ["🍦", "soft ice cream dessert"],
    ["🥧", "pie dessert"],
    ["🧁", "cupcake dessert"],
    ["🍰", "shortcake cake dessert birthday"],
    ["🎂", "birthday cake"],
    ["🍮", "custard pudding flan"],
    ["🍭", "lollipop candy"],
    ["🍬", "candy sweet"],
    ["🍫", "chocolate bar"],
    ["🍿", "popcorn movie"],
    ["🍩", "doughnut donut dessert"],
    ["🍪", "cookie"],
    ["🥛", "glass of milk"],
    ["☕", "hot beverage coffee tea"],
    ["🍵", "teacup without handle tea green"],
    ["🧃", "beverage box juice"],
    ["🥤", "cup with straw soda"],
    ["🧋", "bubble tea boba"],
    ["🍺", "beer mug drink"],
    ["🍻", "clinking beer mugs cheers"],
    ["🥂", "clinking glasses champagne cheers toast"],
    ["🍷", "wine glass drink"],
    ["🥃", "tumbler glass whiskey"],
    ["🍸", "cocktail glass drink"],
    ["🍹", "tropical drink cocktail"],
    ["🧉", "mate drink"],
    ["🍾", "bottle popping cork champagne celebration"],
  ]),
  category("activity", [
    ["⚽", "soccer ball football sport"],
    ["🏀", "basketball sport"],
    ["🏈", "american football sport"],
    ["⚾", "baseball sport"],
    ["🥎", "softball sport"],
    ["🎾", "tennis sport"],
    ["🏐", "volleyball sport"],
    ["🏉", "rugby football sport"],
    ["🥏", "flying disc frisbee"],
    ["🎱", "pool 8 ball billiards"],
    ["🏓", "ping pong table tennis"],
    ["🏸", "badminton"],
    ["🏒", "ice hockey"],
    ["🥍", "lacrosse"],
    ["🏏", "cricket game"],
    ["⛳", "flag in hole golf"],
    ["🏹", "bow and arrow archery"],
    ["🎣", "fishing pole"],
    ["🥊", "boxing glove"],
    ["🥋", "martial arts uniform judo karate"],
    ["🎽", "running shirt"],
    ["🛹", "skateboard"],
    ["⛸️", "ice skate"],
    ["🥌", "curling stone"],
    ["🎿", "skis skiing"],
    ["⛷️", "skier"],
    ["🏂", "snowboarder"],
    ["🏋️", "person lifting weights gym workout"],
    ["🤼", "people wrestling"],
    ["🤺", "person fencing"],
    ["🏇", "horse racing"],
    ["🏆", "trophy win champion"],
    ["🥇", "first place medal gold win"],
    ["🥈", "second place medal silver"],
    ["🥉", "third place medal bronze"],
    ["🏅", "sports medal"],
    ["🎖️", "military medal"],
    ["🎗️", "reminder ribbon"],
    ["🎫", "ticket event"],
    ["🎪", "circus tent"],
    ["🤹", "person juggling"],
    ["🎭", "performing arts theater masks"],
    ["🩰", "ballet shoes dance"],
    ["🎨", "artist palette art paint"],
    ["🎬", "clapper board movie film action"],
    ["🎤", "microphone sing karaoke"],
    ["🎧", "headphone music listen"],
    ["🎼", "musical score"],
    ["🎹", "musical keyboard piano"],
    ["🥁", "drum music"],
    ["🎷", "saxophone jazz music"],
    ["🎺", "trumpet music"],
    ["🎸", "guitar rock music"],
    ["🪕", "banjo music"],
    ["🎻", "violin music"],
    ["🎲", "game die dice random"],
    ["♟️", "chess pawn strategy"],
    ["🎯", "bullseye dart target direct hit"],
    ["🎳", "bowling"],
    ["🎮", "video game controller gaming"],
    ["🎰", "slot machine casino"],
    ["🧩", "puzzle piece jigsaw"],
  ]),
  category("travel", [
    ["🚗", "automobile car red"],
    ["🚕", "taxi cab"],
    ["🚙", "sport utility vehicle suv car"],
    ["🚌", "bus"],
    ["🚎", "trolleybus"],
    ["🏎️", "racing car f1"],
    ["🚓", "police car"],
    ["🚑", "ambulance emergency"],
    ["🚒", "fire engine truck"],
    ["🚐", "minibus van"],
    ["🛻", "pickup truck"],
    ["🚚", "delivery truck"],
    ["🚜", "tractor farm"],
    ["🛴", "kick scooter"],
    ["🚲", "bicycle bike"],
    ["🛵", "motor scooter vespa"],
    ["🏍️", "motorcycle"],
    ["🚨", "police car light siren emergency"],
    ["🚂", "locomotive train steam"],
    ["🚆", "train"],
    ["🚇", "metro subway"],
    ["🚈", "light rail"],
    ["🚄", "high speed train bullet"],
    ["🚝", "monorail"],
    ["🚞", "mountain railway"],
    ["✈️", "airplane flight plane"],
    ["🛫", "airplane departure takeoff"],
    ["🛬", "airplane arrival landing"],
    ["🚀", "rocket launch space ship"],
    ["🛸", "flying saucer ufo"],
    ["🚁", "helicopter"],
    ["⛵", "sailboat sailing"],
    ["🚤", "speedboat"],
    ["🛥️", "motor boat"],
    ["🚢", "ship cruise"],
    ["⚓", "anchor sea"],
    ["🗺️", "world map travel"],
    ["🧭", "compass navigation"],
    ["🏔️", "snow capped mountain"],
    ["⛰️", "mountain"],
    ["🌋", "volcano"],
    ["🏕️", "camping tent"],
    ["🏖️", "beach umbrella vacation"],
    ["🏜️", "desert"],
    ["🏝️", "desert island"],
    ["🏞️", "national park"],
    ["🏟️", "stadium"],
    ["🏛️", "classical building"],
    ["🏗️", "building construction"],
    ["🏠", "house home"],
    ["🏡", "house garden home"],
    ["🏢", "office building work"],
    ["🏥", "hospital"],
    ["🏦", "bank"],
    ["🏨", "hotel"],
    ["🏫", "school"],
    ["⛪", "church"],
    ["🕌", "mosque"],
    ["🕍", "synagogue"],
    ["🗼", "tokyo tower"],
    ["🗽", "statue of liberty new york"],
    ["🌉", "bridge at night"],
    ["🌁", "foggy"],
    ["🎡", "ferris wheel"],
    ["🎢", "roller coaster"],
    ["⛲", "fountain"],
    ["🌅", "sunrise morning"],
    ["🌄", "sunrise over mountains"],
    ["🌇", "sunset evening city"],
    ["🌆", "cityscape at dusk evening"],
    ["🏙️", "cityscape skyline"],
    ["🌃", "night with stars city"],
    ["🛣️", "motorway highway road"],
    ["🛤️", "railway track"],
    ["🗾", "map of japan"],
    ["⏰", "alarm clock morning wake"],
    ["⌛", "hourglass done time"],
    ["⏳", "hourglass not done waiting time"],
    ["🧳", "luggage travel suitcase"],
    ["🎒", "backpack school bag"],
    ["🗿", "moai easter island"],
  ]),
  category("objects", [
    ["⌚", "watch time"],
    ["📱", "mobile phone smartphone"],
    ["💻", "laptop computer"],
    ["⌨️", "keyboard typing"],
    ["🖥️", "desktop computer"],
    ["🖨️", "printer"],
    ["🖱️", "computer mouse"],
    ["🕹️", "joystick game"],
    ["💽", "computer disk minidisc"],
    ["💾", "floppy disk save"],
    ["💿", "optical disk cd"],
    ["📀", "dvd"],
    ["📼", "videocassette vhs tape"],
    ["📷", "camera photo"],
    ["📸", "camera flash photo"],
    ["📹", "video camera"],
    ["🎥", "movie camera film"],
    ["📞", "telephone receiver call"],
    ["☎️", "telephone phone call"],
    ["📟", "pager"],
    ["📠", "fax machine"],
    ["📺", "television tv"],
    ["📻", "radio"],
    ["🎙️", "studio microphone podcast"],
    ["🎚️", "level slider"],
    ["🎛️", "control knobs"],
    ["🧭", "compass navigation direction"],
    ["⏱️", "stopwatch timer"],
    ["⏲️", "timer clock"],
    ["🕰️", "mantelpiece clock"],
    ["🔋", "battery charge"],
    ["🔌", "electric plug charge"],
    ["💡", "light bulb idea"],
    ["🔦", "flashlight torch"],
    ["🕯️", "candle light"],
    ["🧯", "fire extinguisher"],
    ["🛢️", "oil drum"],
    ["💸", "money wings spending"],
    ["💵", "dollar banknote money cash"],
    ["💰", "money bag rich cash"],
    ["💳", "credit card payment"],
    ["💎", "gem stone diamond jewel"],
    ["⚖️", "balance scale justice law"],
    ["🧰", "toolbox tools"],
    ["🔧", "wrench tool fix"],
    ["🔨", "hammer tool build"],
    ["⚒️", "hammer and pick tools"],
    ["🛠️", "hammer and wrench tools"],
    ["⛏️", "pick mining"],
    ["🔩", "nut and bolt hardware"],
    ["⚙️", "gear settings"],
    ["🧲", "magnet attract"],
    ["🔫", "water pistol gun"],
    ["💣", "bomb explosive"],
    ["🧨", "firecracker dynamite"],
    ["🔪", "kitchen knife cooking"],
    ["🗡️", "dagger sword"],
    ["⚔️", "crossed swords battle"],
    ["🛡️", "shield protect"],
    ["🚬", "cigarette smoking"],
    ["⚰️", "coffin death"],
    ["🏺", "amphora vase"],
    ["🔮", "crystal ball fortune future"],
    ["📿", "prayer beads"],
    ["🧿", "nazar amulet evil eye"],
    ["💈", "barber pole haircut"],
    ["⚗️", "alembic chemistry"],
    ["🔭", "telescope space stars"],
    ["🔬", "microscope science"],
    ["🕳️", "hole"],
    ["💊", "pill medicine drug"],
    ["💉", "syringe vaccine injection"],
    ["🩸", "drop of blood"],
    ["🧬", "dna genetics"],
    ["🦠", "microbe virus germ"],
    ["🧫", "petri dish"],
    ["🧪", "test tube science"],
    ["🌡️", "thermometer temperature fever"],
    ["🧹", "broom clean sweep"],
    ["🧺", "basket laundry"],
    ["🧻", "roll of paper toilet"],
    ["🚽", "toilet"],
    ["🚰", "potable water tap"],
    ["🚿", "shower bath"],
    ["🛁", "bathtub bath"],
    ["🧼", "soap clean"],
    ["🪥", "toothbrush"],
    ["🧽", "sponge clean"],
    ["🔑", "key lock"],
    ["🗝️", "old key lock"],
    ["🚪", "door"],
    ["🪑", "chair seat"],
    ["🛋️", "couch and lamp sofa"],
    ["🛏️", "bed sleep"],
    ["🧸", "teddy bear toy"],
    ["🖼️", "framed picture art"],
    ["🛍️", "shopping bags"],
    ["🛒", "shopping cart groceries"],
    ["🎁", "wrapped gift present"],
    ["🎈", "balloon party"],
    ["🎏", "carp streamer"],
    ["🎀", "ribbon bow"],
    ["🎊", "confetti ball party celebration"],
    ["🎉", "party popper celebration tada"],
    ["🪄", "magic wand"],
    ["📮", "postbox mail"],
    ["📦", "package box delivery"],
    ["📫", "open mailbox raised flag"],
    ["✉️", "envelope mail letter"],
    ["📧", "e-mail email"],
    ["📅", "calendar date"],
    ["📈", "chart increasing up trend graph"],
    ["📉", "chart decreasing down trend graph"],
    ["📊", "bar chart stats graph"],
    ["📋", "clipboard"],
    ["📁", "file folder"],
    ["📂", "open file folder"],
    ["🗂️", "card index dividers"],
    ["🗞️", "rolled up newspaper news"],
    ["📰", "newspaper news"],
    ["📓", "notebook"],
    ["📔", "notebook decorative cover"],
    ["📒", "ledger notebook"],
    ["📕", "closed book red"],
    ["📗", "green book"],
    ["📘", "blue book"],
    ["📙", "orange book"],
    ["📚", "books library study"],
    ["📖", "open book read"],
    ["🔖", "bookmark"],
    ["🧷", "safety pin"],
    ["🔗", "link chain url"],
    ["📎", "paperclip attachment"],
    ["🖇️", "linked paperclips"],
    ["✂️", "scissors cut"],
    ["📐", "triangular ruler"],
    ["📏", "straight ruler measure"],
    ["🖊️", "pen write"],
    ["🖋️", "fountain pen write"],
    ["✒️", "black nib pen"],
    ["🖌️", "paintbrush art"],
    ["🖍️", "crayon"],
    ["📝", "memo note write pencil"],
    ["✏️", "pencil write edit"],
    ["🔍", "magnifying glass tilted left search"],
    ["🔎", "magnifying glass tilted right search"],
    ["🔏", "locked with pen private"],
    ["🔐", "locked with key secure"],
    ["🔒", "locked lock private"],
    ["🔓", "unlocked open lock"],
  ]),
  category("symbols", [
    ["❤️", "red heart love"],
    ["🧡", "orange heart love"],
    ["💛", "yellow heart love"],
    ["💚", "green heart love"],
    ["💙", "blue heart love"],
    ["💜", "purple heart love"],
    ["🖤", "black heart"],
    ["🤍", "white heart"],
    ["🤎", "brown heart"],
    ["💔", "broken heart"],
    ["❣️", "heart exclamation"],
    ["💕", "two hearts love"],
    ["💞", "revolving hearts"],
    ["💓", "beating heart"],
    ["💗", "growing heart"],
    ["💖", "sparkling heart"],
    ["💘", "heart with arrow cupid"],
    ["💝", "heart with ribbon gift"],
    ["💟", "heart decoration"],
    ["☮️", "peace symbol"],
    ["✝️", "latin cross"],
    ["☪️", "star and crescent"],
    ["🕉️", "om"],
    ["☸️", "wheel of dharma"],
    ["✡️", "star of david"],
    ["☯️", "yin yang"],
    ["♈", "aries zodiac"],
    ["♉", "taurus zodiac"],
    ["♊", "gemini zodiac"],
    ["♋", "cancer zodiac"],
    ["♌", "leo zodiac"],
    ["♍", "virgo zodiac"],
    ["♎", "libra zodiac"],
    ["♏", "scorpio zodiac"],
    ["♐", "sagittarius zodiac"],
    ["♑", "capricorn zodiac"],
    ["♒", "aquarius zodiac"],
    ["♓", "pisces zodiac"],
    ["🆔", "id button identification"],
    ["⚛️", "atom symbol science"],
    ["☢️", "radioactive"],
    ["☣️", "biohazard"],
    ["📴", "mobile phone off"],
    ["📳", "vibration mode"],
    ["✅", "check mark button done yes correct"],
    ["✔️", "check mark done yes correct"],
    ["❌", "cross mark no wrong x"],
    ["❎", "cross mark button no"],
    ["➕", "plus add"],
    ["➖", "minus subtract"],
    ["➗", "divide division"],
    ["✖️", "multiply multiplication"],
    ["💲", "heavy dollar sign money"],
    ["💱", "currency exchange"],
    ["©️", "copyright"],
    ["®️", "registered trademark"],
    ["™️", "trade mark"],
    ["🔝", "top arrow"],
    ["🔙", "back arrow"],
    ["🔛", "on arrow"],
    ["🔜", "soon arrow"],
    ["🔚", "end arrow"],
    ["➡️", "right arrow"],
    ["⬅️", "left arrow"],
    ["⬆️", "up arrow"],
    ["⬇️", "down arrow"],
    ["↩️", "right arrow curving left reply"],
    ["↪️", "left arrow curving right forward"],
    ["🔄", "counterclockwise arrows refresh reload"],
    ["🔃", "clockwise vertical arrows refresh"],
    ["🔀", "shuffle tracks random"],
    ["🔁", "repeat button loop"],
    ["🔂", "repeat single once"],
    ["▶️", "play button"],
    ["⏸️", "pause button"],
    ["⏹️", "stop button"],
    ["⏺️", "record button"],
    ["⏭️", "next track button"],
    ["⏮️", "last track button"],
    ["⏩", "fast forward button"],
    ["⏪", "rewind button fast reverse"],
    ["🔼", "upwards button"],
    ["🔽", "downwards button"],
    ["🎦", "cinema movie"],
    ["🔅", "dim button brightness low"],
    ["🔆", "bright button brightness high"],
    ["📶", "antenna bars signal"],
    ["♻️", "recycling symbol recycle green"],
    ["⚜️", "fleur de lis"],
    ["🔱", "trident emblem"],
    ["📛", "name badge"],
    ["🔰", "japanese symbol beginner"],
    ["⭕", "hollow red circle correct o"],
    ["🚫", "prohibited forbidden no"],
    ["❗", "red exclamation mark important"],
    ["❓", "red question mark"],
    ["❔", "white question mark"],
    ["❕", "white exclamation mark"],
    ["💯", "hundred points perfect score 100"],
    ["🔞", "no one under eighteen"],
    ["📵", "no mobile phones"],
    ["🚭", "no smoking"],
    ["🚯", "no littering"],
    ["🚱", "non potable water"],
    ["🚷", "no pedestrians"],
    ["⚠️", "warning caution"],
    ["🚸", "children crossing"],
    ["🔕", "bell with slash mute silent"],
    ["🔔", "bell notification"],
    ["♾️", "infinity forever"],
    ["💤", "zzz sleep"],
    ["🗯️", "right anger bubble"],
    ["💬", "speech balloon comment chat"],
    ["💭", "thought balloon thinking"],
    ["🕐", "one o'clock time"],
    ["🔟", "keycap 10 ten"],
  ]),
];

/** Mirrors RECENT_EMOJIS_MAX in backend/src/domain/preferences/user-preferences.ts. */
export const RECENT_EMOJIS_MAX = 24;

/** All entries across categories, for search. */
export const ALL_EMOJIS: ReadonlyArray<EmojiEntry> = EMOJI_CATEGORIES.flatMap(
  (group) => group.entries,
);

/** Case-insensitive substring search over every entry's name. */
export function searchEmojis(query: string): ReadonlyArray<EmojiEntry> {
  const term = query.trim().toLowerCase();
  if (!term) return [];
  return ALL_EMOJIS.filter((entry) => entry.name.includes(term));
}
